version: 2.1

orbs:
  codacy: codacy/base@10.9.1
  codacy_plugins_test: codacy/plugins-test@1.1.1

jobs:
  dotnet:
    parameters:
      cmd:
        type: string
        description: "The command to run"
      persist_to_workspace:
        type: boolean
        description: "Whether to persist the workspace or not at the end of the job"
        default: false
      cache_bootstrap:
        type: boolean
        description: "Whether to cache bootstrap files"
        default: false
    docker:
      - image: mcr.microsoft.com/dotnet/aspnet:7.0-jammy
    working_directory: ~/workdir
    steps:
      - when:
          condition: << parameters.cache_bootstrap >>
          steps:
            - restore_cache:
                keys:
                  - cache-bootstrap-tsqllint-v1-{{ checksum "tsqllint.version" }}
                  - cache-bootstrap-tsqllint-v1-
      - run:
          name: Install packages
          command: |
            apt update
            apt install -y ca-certificates gnupg
            gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
            apt update
            apt install -y mono-complete build-essential nuget
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Run command - << parameters.cmd >>
          command: << parameters.cmd >>
      - when:
          condition: << parameters.cache_bootstrap >>
          steps:
            - save_cache:
                key: cache-bootstrap-tsqllint-v1-{{ checksum "tsqllint.version" }}
                paths:
                  - ".resources"
      - when:
          condition: << parameters.persist_to_workspace >>
          steps:
            - persist_to_workspace:
                root: ~/workdir
                paths:
                  - "*"

workflows:
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - dotnet:
          name: build
          cmd: |
            ./scripts/bootstrap.sh
            dotnet build
          persist_to_workspace: true
          cache_bootstrap: true
          requires:
            - codacy/checkout_and_version
      - dotnet:
          name: test
          cmd: dotnet test
          persist_to_workspace: true
          requires:
            - build
      - dotnet:
          name: publish_local
          cmd: dotnet publish -c Release
          persist_to_workspace: true
          requires:
            - test
      - codacy/shell:
           name: publish_docker_local
           cmd: |
             docker build -t $CIRCLE_PROJECT_REPONAME:latest .
             docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
           persist_to_workspace: true
           requires:
             - codacy/checkout_and_version
             - publish_local
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
